config/routes.rb
Rails.application.routes.draw do

  resources :evaluaciones do
    get 'listado', :on => :collection
  end

  resources :administrador do
    get 'index', :on => :collection
  end

  get 'inicio/index'

  resources :subtitulos do
    get 'listado', :on => :collection
  end

	resources :audios do
    get 'listado', :on => :collection
  end
	resources :transcripciones do
    get 'listado', :on => :collection
  end
	
	resources :cursos do
    get 'listado', :on => :collection
  end
  resources :universidades do
    get 'listado', :on => :collection
  end
	resources :proveedores do
    get 'listado', :on => :collection
  end
  resources :idiomas do
    get 'listado', :on => :collection
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
	resources :users do
		get 'listado', :on => :collection
	end
  resources :home do
    get 'index', :on => :collection
  end
	
  root 'home#index'
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
  has_many :subtitulos

  has_many :audios

  has_many :transcripciones

  def to_s
    descripcion
  end

end

app/controllers/idiomas_controller.rb
# -*- encoding : utf-8 -*-
class IdiomasController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource #skip_load_resource only: [:create] 
  skip_load_resource only: [:create] 
  
  before_action :set_idioma, only: [:show, :edit, :update, :destroy]

  layout 'administrador'

  def listado
    datos = []
    Idioma.all.each do |j| 
      datos << j.descripcion 
    end

    render :json => datos.to_json
  end


  def index
#    @idiomas = Idioma.all
    @idiomas = Idioma.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @subtitulos = @idioma.subtitulos.paginate(:page => params[:page], :per_page => 20)

    @audios = @idioma.audios.paginate(:page => params[:page], :per_page => 20)

    @transcripciones = @idioma.transcripciones.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @idioma = Idioma.new
  end

  def edit
  end

  def create
    @idioma = Idioma.new(idioma_params)

    if @idioma.save
      redirect_to idiomas_url, notice: t('mio.create_idioma')
    else
      render action: 'new'
    end
  end

  def update
    if @idioma.update(idioma_params)
      redirect_to @idioma, notice: t('mio.update_idioma')
    else
      render action: 'edit'
    end
  end

  def destroy
    @idioma.destroy
    redirect_to idiomas_url, notice: t('mio.destroy_idioma')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idioma
      @idioma = Idioma.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def idioma_params
      #params.require(:idioma).permit(:descripcion)

      params.require(:idioma).permit(:descripcion)
    end
end

app/views/idiomas/_form.html.erb
<div class="col-md-12">
  <div class="well col-md-12 col-md-offset-0">
    <%= form_for(@idioma, :html => { :class => "form-horizontal" }) do |f| %>
      <% if @idioma.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= I18n.t("errors.messages.not_saved", :count => @idioma.errors.count, :resource => "idioma") %></h4>

          <ul>
          <% @idioma.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <div class="form-group">
          <%= f.label t('mio.campo_descripcion'), :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :descripcion, :class => "form-control" %>
          </div>
      </div>
      <div class="panel-footer">
        <button type="submit" class="btn btn-primary" id="boton_aceptar">
          <i class="glyphicon glyphicon-ok-sign"></i> 
          <%= @idioma.new_record? ? "#{t('helpers.links.create')} #{t('mio.idioma')}" : "#{t('helpers.links.update')} #{t('mio.idioma')}" %>
        </button>
        <%= link_to idiomas_path, :class => 'btn btn-default' do %>
          <span class="glyphicon glyphicon-remove-sign"></span>
          <%= t('helpers.links.cancel') %>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/idiomas/_tabla.html.erb
    <div class="pagination">
      <%= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-condensed table-striped table-hover">
      <thead>
        <tr>
          <th><%= t('mio.campo_descripcion') %></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, registros) do |idioma| %>
          <td><%= link_to idioma.descripcion, idioma %></td>
        <% end -%>
      </tbody>
    </table>

    <div class="pagination">
      <%#= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

app/views/idiomas/edit.html.erb
<% breadcrumb :idioma, @idioma %>

<%= render 'form' %>

app/views/idiomas/index.html.erb
<% breadcrumb :idiomas %>

<div class="col-md-12">
  <div class="well-sombra well col-md-12 col-md-offset-0">
  <%= link_to new_idioma_path, :class => 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= "#{t('helpers.links.new')} #{t('mio.idioma')}" %>
    <% end %>

    <%= render partial: 'tabla', locals: {registros: @idiomas} %>

  </div>
 </div>

app/views/idiomas/new.html.erb
<% breadcrumb :idioma_nuevo %>

<%= render 'form' %>

app/views/idiomas/show.html.erb
<% breadcrumb :idioma, @idioma %>

<%- model_class = Idioma -%>
<div class="col-md-12">
  <div class="well col-md-12 ">
    <dl class="dl-horizontal">
      <dt><%= t('mio.campo_descripcion') %>:</dt>
      <dd><%= @idioma.descripcion %></dd>

    </dl>

    <div class="panel-footer">
      <%= link_to idiomas_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        <%= t('.back', :default => t("helpers.links.back", :default => 'Volver')) %>
      <% end %>
      <%= link_to edit_idioma_path(@idioma), :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-pencil"></span>
        <%= t('.edit', :default => t("helpers.links.edit", :default => 'Editar')) %>
      <% end %>

      <%= link_to idioma_path(@idioma), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Eliminar el idioma '#{@idioma.id}'?")) }, :class => 'btn btn-danger' do %>
        <span class="glyphicon glyphicon-trash"></span>
        <%= t('.destroy', :default => t("helpers.links.destroy")) %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-12">
  <div class="well">
    <h3><%= t('mio.idioma_show_1') %></h3>
    <% unless @audios.nil? -%>
      <% unless @audios.empty? -%>
        <%= render partial: "audios/tabla3", locals: {registros: @audios} %>
      <% end -%>
    <% end -%>
  </div>
</div>

<div class="col-md-12">
  <div class="well">
    <h3><%= t('mio.idioma_show_2') %></h3>
    <% unless @subtitulos.nil? -%>
      <% unless @subtitulos.empty? -%>
        <%= render partial: "subtitulos/tabla3", locals: {registros: @subtitulos} %>
      <% end -%>
    <% end -%>
  </div>
</div>

<div class="col-md-12">
  <div class="well">
    <h3><%= t('mio.idioma_show_3') %></h3>
    <% unless @transcripciones.nil? -%>
      <% unless @transcripciones.empty? -%>
        <%= render partial: "transcripciones/tabla3", locals: {registros: @transcripciones} %>
      <% end -%>
    <% end -%>
  </div>
</div>