config/routes.rb
Rails.application.routes.draw do

  resources :evaluaciones do
    get 'listado', :on => :collection
  end

  resources :administrador do
    get 'index', :on => :collection
  end

  get 'inicio/index'

  resources :subtitulos do
    get 'listado', :on => :collection
  end

	resources :audios do
    get 'listado', :on => :collection
  end
	resources :transcripciones do
    get 'listado', :on => :collection
  end
	
	resources :cursos do
    get 'listado', :on => :collection
  end
  resources :universidades do
    get 'listado', :on => :collection
  end
	resources :proveedores do
    get 'listado', :on => :collection
  end
  resources :idiomas do
    get 'listado', :on => :collection
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
	resources :users do
		get 'listado', :on => :collection
	end
  resources :home do
    get 'index', :on => :collection
  end
	
  root 'home#index'
end

app/models/curso.rb
class Curso < ActiveRecord::Base
	has_and_belongs_to_many :users
  
  has_many :evaluaciones

  has_many :subtitulos

  has_many :audios

  has_many :transcripciones

	belongs_to :proveedor

	belongs_to :universidad

#	validates_uniqueness_of :edicion_anterior_id

  has_attached_file :imagen

	validates_attachment_content_type :imagen, :content_type => [
							'image/jpg',
							'image/jpeg',
							'image/pjpeg',
							'image/png',
							'image/x-png',
							'image/gif',
							'application/binary',
							'application/pdf',
							'application/x-pdf',
							'application/x-download', 
							'application/msword',
							'applicationvnd.ms-word',
							'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
							'application/msexcel',
							'application/vnd.ms-excel',
							'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
							'application/mspowerpoint',
							'application/vnd.ms-powerpoint',
							'application/vnd.openxmlformats-officedocument.presentationml.presentation',
							'text/plain',
							'application/rtf']

	def self.order_by_ids(ids)
	  order_by = ["CASE"]
	  ids.each_with_index do |id, index|
	    order_by << "WHEN id='#{id}' THEN #{index}"
	  end
	  order_by << "END"
	  order(order_by.join(" "))
	end

	def tematica_sin_html
		return '' if self.tematica.nil? 

#		self.tematica.gsub(/<([^>]*)>/,'') #.gsub(/<script>*<\/script>/)
#		self.tematica.gsub(/\<(/?[^\>]+)\>/,'') #.gsub(/<script>*<\/script>/)
#		self.tematica.gsub(/'<script'*'script>'/)
#		self.tematica
		texto = self.tematica.gsub(/<script[^>]*>(.*?)<\/script>/,'')
		texto = texto.gsub(/<(.*?)>/,'')
		texto = texto.gsub(/Badges y certificados/,'')
#		texto = texto.gsub(/\n\r/,'')
#		texto = texto.gsub(/AUI\(\)\.ready(.*?)addClass\(cssClass\); \}/,'')
#		texto = texto.gsub(/\{(.*?)\}/,'')

    texto = texto.gsub(/^\s+/,'').gsub(/\n/,'<br />').html_safe

		texto = texto[0, 1000] if texto.length > 1500 
		return texto
	end

	def edicion_anterior_nombre
		return Curso.find(self.edicion_anterior_id).nil? ? "" : Curso.find(self.edicion_anterior_id)  
	end

	def edicion_anterior_nombre=(valor)
		self.edicion_anterior_id = Curso.find_by_nombre(valor).id
	end

  def imagen_from_url(url)
    self.imagen = open(URI.escape(url))
  end

	def proveedor_nombre
		return self.proveedor.nil? ? "" : self.proveedor.nombre 
	end

	def proveedor_nombre=(valor)
		self.proveedor = Proveedor.find_by_nombre(valor)
	end

	def universidad_nombre
		return self.universidad.nil? ? "" : self.universidad.nombre 
	end

	def universidad_nombre=(valor)
		self.universidad = Universidad.find_by_nombre(valor)
	end

	def puntuacion_estrella
		x = self.puntuacion

		x = -1 * x 

		x = x * 10

		case x
		when 0..14
			return '00'
		when 05..19
			return '05'
		when 20..24
			return '20'
		when 25..29
			return '25'
		when 30..34
			return '30'
		when 35..39
			return '35'
		when 40..44
			return '40'
		when 45..49
			return '45'
		when 50
			return '50'
		else
			return '00'
		end		
	end

	def mostrar_puntuacion
		x = -1 * self.puntuacion 

		return ' ' + x.round(2).to_s
	end

	def puntuacion
		suma = 0.0

		cuantos = 0

		tmp = self
		ant = self
		
		unless tmp.edicion_anterior_id.nil? then
			tmp = Curso.find(tmp.edicion_anterior_id)
			while not tmp.nil? and not tmp.edicion_anterior_id.nil?
	      if tmp.id == self.id then
	        tmp = nil
	      else
	      	if tmp.edicion_anterior_id.nil?
	      		ant = tmp
	      		tmp = nil
	      	else
						tmp = Curso.find(tmp.edicion_anterior_id)
					end
	      end
			end 
		end

		while not ant.nil?
			ant.evaluaciones.each do |e|
				suma = suma + e.media
				cuantos = cuantos + 1
			end

			ant = Curso.find_by_edicion_anterior_id(ant.id)

      unless ant.nil? then
	      if ant.id == self.id then
	        ant = nil
	      end
	    end
		end

		if cuantos == 0 then
			return 0
		else
			return -1 * (suma / cuantos)
		end
	end

	def puntuacion_texto
		suma = 0.0
		suma_motivacion = 0.0
		suma_representacion = 0.0
		suma_expresion = 0.0

		cuantos = 0

		tmp = self
		ant = self
		
		unless tmp.edicion_anterior_id.nil? then
			tmp = Curso.find(tmp.edicion_anterior_id)
			while not tmp.nil? and not tmp.edicion_anterior_id.nil?
	      if tmp.id == self.id then
	        tmp = nil
	      else
	      	if tmp.edicion_anterior_id.nil?
	      		ant = tmp
	      		tmp = nil
	      	else
						tmp = Curso.find(tmp.edicion_anterior_id)
					end
	      end
			end 
		end

		while not ant.nil?
			ant.evaluaciones.each do |e|
				suma = suma + e.media
				suma_motivacion = suma_motivacion + e.media_motivacion
				suma_representacion = suma_representacion + e.media_representacion
				suma_expresion = suma_expresion + e.media_expresion
				cuantos = cuantos + 1
			end

			ant = Curso.find_by_edicion_anterior_id(ant.id)

      unless ant.nil? then
	      if ant.id == self.id then
	        ant = nil
	      end
	    end
		end

		if cuantos == 0 then
			return 'Sin puntuación'#Esta línea no se puede traducir porque está contemplada en un if
		else
			return ">>>> #{I18n.t('mio.orden_busqueda_puntuacion')}: #{suma / cuantos}, 
							#{I18n.t('mio.evaluacion_motivacion')}: #{suma_motivacion}, 
							#{I18n.t('mio.evaluacion_representacion')}: #{suma_representacion}, 
							#{I18n.t('mio.evaluacion_expresion')}: #{suma_expresion}, 
							#{I18n.t('mio.de')} #{self.evaluaciones.count} #{I18n.t('mio.puntuaciones')}."
		end
	end

	def puntuacion_texto_corto
		suma = 0.0
		suma_motivacion = 0.0
		suma_representacion = 0.0
		suma_expresion = 0.0

		cuantos = 0

		tmp = self
		ant = self
		
		unless tmp.edicion_anterior_id.nil? then
			tmp = Curso.find(tmp.edicion_anterior_id)
			while not tmp.nil? and not tmp.edicion_anterior_id.nil?
	      if tmp.id == self.id then
	        tmp = nil
	      else
	      	if tmp.edicion_anterior_id.nil?
	      		ant = tmp
	      		tmp = nil
	      	else
						tmp = Curso.find(tmp.edicion_anterior_id)
					end
	      end
			end 
		end

		while not ant.nil?
			ant.evaluaciones.each do |e|
				if suma == 0.0 then
					suma = suma + e.media
					suma_motivacion = suma_motivacion + e.media_motivacion
					suma_representacion = suma_representacion + e.media_representacion
					suma_expresion = suma_expresion + e.media_expresion
				else
					suma = (suma + e.media) / 2
					suma_motivacion = (suma_motivacion + e.media_motivacion) / 2
					suma_representacion = (suma_representacion + e.media_representacion) / 2
					suma_expresion = (suma_expresion + e.media_expresion) / 2
				end
				cuantos = cuantos + 1
			end

			ant = Curso.find_by_edicion_anterior_id(ant.id)

      unless ant.nil? then
	      if ant.id == self.id then
	        ant = nil
	      end
	    end
		end

		if cuantos == 0 then
			return 'Sin puntuación' #Esta línea no se puede traducir porque está contemplada en un if
		else
			return "#{I18n.t('mio.evaluacion_motivacion')}: #{suma_motivacion.round(1).to_s}, 
							#{I18n.t('mio.evaluacion_representacion')}: #{suma_representacion.round(1).to_s}, 
							#{I18n.t('mio.evaluacion_expresion')}: #{suma_expresion.round(1).to_s} 
							#{I18n.t('mio.de')} #{self.evaluaciones.count} #{I18n.t('mio.puntuaciones')}." 
							#{'puntuación'.pluralize(self.evaluaciones.count)}."
		end
	end

	def puntuacion_grafico

		suma = 0.0
		suma_motivacion = 0.0
		suma_representacion = 0.0
		suma_expresion = 0.0

		cuantos = 0

		tmp = self
		ant = self
		
		unless tmp.edicion_anterior_id.nil? then
			tmp = Curso.find(tmp.edicion_anterior_id)
			while not tmp.nil? and not tmp.edicion_anterior_id.nil?
	      if tmp.id == self.id then
	        tmp = nil
	      else
	      	if tmp.edicion_anterior_id.nil?
	      		ant = tmp
	      		tmp = nil
	      	else
						tmp = Curso.find(tmp.edicion_anterior_id)
					end
	      end
			end 
		end

		while not ant.nil?
			ant.evaluaciones.each do |e|
				suma = suma + e.media
				suma_motivacion = suma_motivacion + e.media_motivacion
				suma_representacion = suma_representacion + e.media_representacion
				suma_expresion = suma_expresion + e.media_expresion
				cuantos = cuantos + 1
			end

			ant = Curso.find_by_edicion_anterior_id(ant.id)

      unless ant.nil? then
	      if ant.id == self.id then
	        ant = nil
	      end
	    end
		end

		return 'Sin puntuación'	if cuantos == 0 #Esta línea no se puede traducir porque está contemplada en un if

#		datos_grafico = [
#							{name: 'Media motivación', data: {'Puntuación obtenida en la motivación' => suma_motivacion}},
#							{name: 'Media representación', data: {'Puntuación obtenida en la representación' => suma_representacion}}, 
#							{name: 'Media expresión', data: {'Puntuación obtenida en la expresión' => suma_expresion}},
#							{name: 'Media total', data: {'Puntuación obtenida en total' => suma}},
#							]

		suma = suma / cuantos
		suma_motivacion = suma_motivacion / cuantos
		suma_representacion = suma_representacion / cuantos
		suma_expresion = suma_expresion / cuantos

		suma = suma.round(2)
		suma_motivacion = suma_motivacion.round(2)
		suma_representacion = suma_representacion.round(2)
		suma_expresion = suma_expresion.round(2)


		datos_grafico = [{
				name: "#{I18n.t('mio.valor_medio')} #{cuantos} " + "#{I18n.t('mio.puntuaciones')}", 
			  data: {
			  	"#{I18n.t('mio.evaluacion_motivacion')}: #{suma_motivacion}" => suma_motivacion, 
					"#{I18n.t('mio.evaluacion_representacion')}: #{suma_representacion}" => suma_representacion,
					"#{I18n.t('mio.evaluacion_expresion')}: #{suma_expresion}" => suma_expresion,
					"#{I18n.t('mio.total')}: #{suma}" => suma
				}
				}]

		return 	datos_grafico 
	end

  def to_s
    nombre
  end

end

app/controllers/cursos_controller.rb
# -*- encoding : utf-8 -*-
class CursosController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource :except => [:show] #skip_load_resource only: [:create] 
  skip_load_resource only: [:create] 
  
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

#  layout 'administrador'
  layout :evaluacion_layout

  def listado
    datos = []
    Curso.all.each do |j| 
      datos << j.nombre 
    end

    render :json => datos.to_json
  end

  def index
    @cursos = Curso.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @evaluaciones = @curso.evaluaciones.order('created_at desc').paginate(:page => params[:page], :per_page => 20)

    @subtitulos = @curso.subtitulos.paginate(:page => params[:page], :per_page => 20)

    @audios = @curso.audios.paginate(:page => params[:page], :per_page => 20)

    @transcripciones = @curso.transcripciones.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @curso = Curso.new
    @listado_cursos = Curso.all.collect {|p| [ p.nombre, p.id ] }
  end

  def edit
    listado_cursos_inteligente
  end

  def create
    @curso = Curso.new(curso_params)

    if @curso.save
      redirect_to cursos_url, notice: t('mio.create_curso')
    else
      render action: 'new'
    end
  end

  def update

    llave = true 

    unless params[:curso][:edicion_anterior_id].nil? or params[:curso][:edicion_anterior_id].empty?

      tmp = Curso.find(params[:curso][:edicion_anterior_id])

      while not tmp.nil?
        if tmp.id == @curso.id then
          tmp = nil
          llave = false
        end

        if llave
          if tmp.edicion_anterior_id.nil? then
            tmp = nil
          else
            tmp = Curso.find(tmp.edicion_anterior_id)
          end
        end
      end
    end

    if llave and @curso.update(curso_params)
#    if @curso.update(curso_params)
      redirect_to @curso, notice: t('mio.update_curso')
    else
      listado_cursos_inteligente
      flash[:error] = t('mio.update_curso_error')
      render action: 'edit'
    end
  end

  def destroy
    @curso.destroy
    redirect_to cursos_url, notice: t('mio.destroy_curso')
  end

  private
    def evaluacion_layout
      return "application" if current_user.nil?

      if current_user.has_role? 'administrador' 
        return "administrador"
      else
        return "inicio"
      end
    end
 
    def listado_cursos_inteligente
      require 'fuzzystringmatch'
      jarow = FuzzyStringMatch::JaroWinkler.create( :native )
      @listado_cursos = []

      Curso.all.each do |c|
        unless @curso.nombre == c.nombre then
          if jarow.getDistance(@curso.nombre, c.nombre) > 0.75 then
            @listado_cursos << [ c.nombre, c.id ]
          end
        end       
      end

#      @listado_cursos = Curso.order('nombre').all.collect {|p| [ p.nombre, p.id ] }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def curso_params
      #params.require(:curso).permit(:identificador, :url, :nombre, :imagen, :proveedor_id, :universidad_id, :tematica, :informacion, :conocimientos_previos, :esfuerzo_estimado, :lenguaje_signos, :precio_auditado, :precio_credencial)
            
      params.require(:curso).permit(
            :identificador, 
            :url, 
            :nombre, 
            :imagen, 
            :proveedor_id, 
            :universidad_id, 
            :tematica, 
            :informacion, 
            :conocimientos_previos, 
            :esfuerzo_estimado, 
            :lenguaje_signos, 
            :precio_auditado, 
            :precio_credencial, 
            :objetivos, 
            :destinatarios, 
            :evaluacion, 
            :inicio, 
            :oculto,
            :edicion_anterior_id,
            :edicion_anterior_nombre)
    end
end

app/views/cursos/_show_admin.html.erb
<%- model_class = Curso -%>
<div class="col-md-12">
  <div class="well col-md-12 ">
    <dl class="dl-horizontal">
      <p>
        <dt>
          <%= t('mio.curso_calificacion') %>:<%= @curso.mostrar_puntuacion %>
        </dt>
        <dd>
          <% if Evaluacion.where("curso_id = #{@curso.id}").count == 0 %>
            <%= t('mio.sin_puntuacion') %>
          <% else %>
            <div class="stars-fieldset">
              <span class="stars stars-<%= @curso.puntuacion_estrella %>"></span>
            </div> 
          <% end %>
        </dd>
      </p>
      <p>
        <dt><%= t('mio.curso_puntuar') %></dt>
        <dd>
          <% if Evaluacion.where("user_id = #{current_user.id} and curso_id = #{@curso.id}").count == 0 %>
            <%= link_to t('mio.votar'), new_evaluacion_url(:user => current_user.id, :curso => @curso.id) %>
          <% else %>
            <%= link_to t('mio.editar_votacion'), @curso.evaluaciones.where("user_id = #{current_user.id}").first %>
            <br /><%= @curso.puntuacion_texto_corto %>
          <% end %>
        </dd>
      </p>
      <p>
      <dt><%= t('mio.curso_oculto') %>:</dt>
      <dd><%= if @curso.oculto then 'Sí' else 'No' end %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_identificador') %>:</dt>
      <dd><%= @curso.identificador %></dd>
      </p>
      <p>
      <dt>Url:</dt>
      <dd><%= @curso.url %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_nombre') %>:</dt>
      <dd><%= @curso.nombre %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_imagen') %>:</dt>
      <dd><%= image_tag(@curso.imagen_url, size: '150x150') %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_plataforma') %>:</dt>
      <dd><%= @curso.proveedor %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_institucion') %>:</dt>
      <dd><%= @curso.universidad %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_tematica') %>:</dt>
      <dd>
        <%= @curso.tematica.gsub(/^\s+/,'').gsub(/\n/,'<br />').html_safe unless @curso.tematica.nil? %>
        <%#= @curso.tematica.html_safe unless @curso.tematica.nil? %>
      </dd>
      </p>
      <p>
      <dt><%= t('mio.curso_informacion') %>:</dt>
      <dd>
        <%= @curso.informacion.gsub(/^\s+/,'').gsub(/\n/,'<br />').html_safe unless @curso.informacion.nil? %>
        <%#= @curso.informacion.html_safe unless @curso.informacion.nil? %>
      </dd>
      </p>
      <p>
      <dt><%= t('mio.curso_objetivos') %>:</dt>
      <dd><%= @curso.objetivos %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_conocimientos') %>:</dt>
      <dd><%= @curso.conocimientos_previos %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_destinatarios') %>:</dt>
      <dd><%= @curso.destinatarios %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_actividades') %>:</dt>
      <dd><%= @curso.evaluacion %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_esfuerzo') %>:</dt>
      <dd><%= @curso.esfuerzo_estimado.html_safe unless @curso.esfuerzo_estimado.nil? %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_proxima') %>:</dt>
      <dd><%= @curso.inicio %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_signos') %>:</dt>
      <dd><%= if @curso.lenguaje_signos then 'Sí' else 'No' end %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_precio_auditado') %>:</dt>
      <dd><%= @curso.precio_auditado %></dd>
      </p>
      <p>
      <dt><%= t('mio.curso_precio_credencial') %>:</dt>
      <dd><%= @curso.precio_credencial %></dd>
      </p>
      <p>
      <p>
      <dt><%= t('mio.curso_edicion_anterior') %>:</dt>
      <dd><%= Curso.find(@curso.edicion_anterior_id).nombre unless @curso.edicion_anterior_id.nil? %></dd>
      </p>
      <dt><%= t('mio.curso_enlace_al') %>:</dt>
      <dd>
        <%= link_to "#{@curso.url}#{@curso.identificador}", :class => 'btn btn-default' do %>
          <span class="glyphicon glyphicon-share"></span>
        <% end -%>
      </dd>
      </p>
    </dl>

    <div class="panel-footer">
      <%= link_to cursos_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        <%= t('.back', :default => t("helpers.links.back", :default => 'Volver')) %>
      <% end %>
      <%= link_to edit_curso_path(@curso), :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-pencil"></span>
        <%= t('.edit', :default => t("helpers.links.edit", :default => 'Editar')) %>
      <% end %>

      <%= link_to curso_path(@curso), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Eliminar el curso '#{@curso.id}'?")) }, :class => 'btn btn-danger' do %>
        <span class="glyphicon glyphicon-trash"></span>
        <%= t('.destroy', :default => t("helpers.links.destroy")) %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="well">
    <%= link_to new_transcripcion_path(:curso_id => @curso.id), :class => 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= "#{t('helpers.links.new')} #{t('mio.transcripcion')}" %>
    <% end %>
    <h3><%= t('mio.transcripciones') %></h3>
    <% unless @transcripciones.nil? -%>
      <% unless @transcripciones.empty? -%>
        <%= render partial: "transcripciones/tabla2", locals: {registros: @transcripciones} %>
      <% end -%>
    <% end -%>
  </div>
</div>

<div class="col-md-4">
  <div class="well">
    <%= link_to new_audio_path(:curso_id => @curso.id), :class => 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= "#{t('helpers.links.new')} #{t('mio.audio')}" %>
    <% end %>
    <h3><%= t('mio.audios') %></h3>
    <% unless @audios.nil? -%>
      <% unless @audios.empty? -%>
        <%= render partial: "audios/tabla2", locals: {registros: @audios} %>
      <% end -%>
    <% end -%>
  </div>
</div>

<div class="col-md-4">
  <div class="well">
    <%= link_to new_subtitulo_path(:curso_id => @curso.id), :class => 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= "#{t('helpers.links.new')} #{t('mio.subtitulo')}" %>
    <% end %>
    <h3><%= t('mio.subtitulos') %></h3>
    <% unless @subtitulos.nil? -%>
      <% unless @subtitulos.empty? -%>
        <%= render partial: "subtitulos/tabla2", locals: {registros: @subtitulos} %>
      <% end -%>
    <% end -%>
  </div>
</div>

<div class="col-md-12">
  <div class="well">
    <h3><%= t('mio.evaluaciones') %></h3>
    <% unless @evaluaciones.nil? -%>
      <% unless @evaluaciones.empty? -%>
        <%= render partial: "evaluaciones/tabla2", locals: {registros: @evaluaciones} %>
      <% end -%>
    <% end -%>
  </div>
</div>

app/views/cursos/_tabla.html.erb
    <div class="pagination">
      <%= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-condensed table-striped table-hover">
      <thead>
        <tr>
					<th><%= t('mio.curso_nombre') %></th>
          <th class='hidden-xs'><%= t('mio.curso_plataforma') %></th>
					<th class='hidden-xs'><%= t('mio.curso_imagen') %></th>
					<th><%= t('mio.curso_institucion') %></th>
					<th class='hidden-xs hidden-sm'><%= t('mio.curso_tematica') %></th>
					<th class='hidden-xs hidden-sm'><%= t('mio.curso_esfuerzo') %></th>
					<th><%= t('mio.curso_enlace') %></th>
				</tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, registros) do |curso| %>
          <td><%= link_to curso.nombre, curso %></td>
          <td class='hidden-xs'><%= curso.proveedor %></td>
					<td class='hidden-xs'><%= image_tag(curso.imagen_url, size: '150x150', alt: "Imagen del curso: #{curso.nombre}") %></td>
          <td><%= curso.universidad %></td>
          <td class='hidden-xs hidden-sm'><%= curso.tematica_sin_html unless curso.tematica.nil? %></td>
          <td class='hidden-xs hidden-sm'><%= curso.esfuerzo_estimado.html_safe unless curso.esfuerzo_estimado.nil? %></td>
          <td>
						<%= link_to "#{curso.url}#{curso.identificador}", :class => 'btn btn-default' do %>
							<span class="glyphicon glyphicon-share" alt="Imagen del curso: <%=curso.nombre%>"></span>
						<% end -%>
					</td>
        <% end -%>
      </tbody>
    </table>

    <div class="pagination">
      <%#= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

app/views/cursos/_tabla2.html.erb
    <div class="pagination">
      <%= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-condensed table-striped table-hover">
      <thead>
        <tr>
					<th><%= t('mio.curso_nombre') %></th>
					<th class='hidden-xs'><%= t('mio.curso_imagen') %></th>
					<th><%= t('mio.curso_institucion') %></th>
					<th class='hidden-xs hidden-sm'><%= t('mio.curso_tematica') %></th>
					<th class='hidden-xs hidden-sm'><%= t('mio.curso_esfuerzo') %></th>
					<th><%= t('mio.curso_enlace') %></th>
				</tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, registros) do |curso| %>
          <td><%= link_to curso.nombre, curso %></td>
					<td class='hidden-xs'><%= image_tag(curso.imagen_url, size: '150x150', alt: "Imagen del curso: #{curso.nombre}") %></td>
          <td><%= curso.universidad %></td>
          <td class='hidden-xs hidden-sm'><%= curso.tematica.html_safe unless curso.tematica.nil? %></td>
          <td class='hidden-xs hidden-sm'><%= curso.esfuerzo_estimado.html_safe unless curso.esfuerzo_estimado.nil? %></td>
          <td>
						<%= link_to "#{curso.url}#{curso.identificador}", :class => 'btn btn-default' do %>
							<span class="glyphicon glyphicon-share" alt="Imagen del curso: <%=curso.nombre%>"></span>
						<% end -%>
					</td>
        <% end -%>
      </tbody>
    </table>

    <div class="pagination">
      <%#= will_paginate registros, renderer: BootstrapPagination::Rails %>
    </div>

app/views/cursos/edit.html.erb
<% breadcrumb :curso, @curso %>

<%= render 'form' %>

app/views/cursos/index.html.erb
<% breadcrumb :cursos %>

<div class="col-md-12">
  <div class="well-sombra well col-md-12 col-md-offset-0">
  <%= link_to new_curso_path, :class => 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= "#{t('helpers.links.new')} #{t('mio.curso')}" %>
    <% end %>

    <%= render partial: 'tabla', locals: {registros: @cursos} %>

  </div>
</div>

app/views/cursos/new.html.erb
<% breadcrumb :cursos_nuevo %>

<%= render 'form' %>