config/routes.rb
Rails.application.routes.draw do

  resources :evaluaciones do
    get 'listado', :on => :collection
  end

  resources :administrador do
    get 'index', :on => :collection
  end

  get 'inicio/index'

  resources :subtitulos do
    get 'listado', :on => :collection
  end

	resources :audios do
    get 'listado', :on => :collection
  end
	resources :transcripciones do
    get 'listado', :on => :collection
  end
	
	resources :cursos do
    get 'listado', :on => :collection
  end
  resources :universidades do
    get 'listado', :on => :collection
  end
	resources :proveedores do
    get 'listado', :on => :collection
  end
  resources :idiomas do
    get 'listado', :on => :collection
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
	resources :users do
		get 'listado', :on => :collection
	end
  resources :home do
    get 'index', :on => :collection
  end
	
  root 'home#index'
end

app/views/layouts/_buscador.html.erb
    <div id='buscador' class='col-lg-8 col-md-7 col-sm-6 col-xs-12'>
  
      <h3><%= t("mio.busqueda_texto") %></h3>

      <%= form_tag home_index_path, :method => :get, :class => 'row', :role => 'search' do %>
        <h3>
          <div class="row form-group">
            <div class='col-lg-10 col-md-10 col-sm-10 col-xs-10'>
              <%= search_field_tag :buscar, @buscar, :placeholder => t("mio.busqueda_interno"), :autofocus => true, :class => 'form-control' %>
            </div>
            <div class='col-lg-2 col-md-2 col-sm-2 col-xs-2'>
              <button type="submit" class="btn btn-default"><span class='glyphicon glyphicon-search'></span></button>
            </div>
          </div>

          <div class="row form-group">
            <div class='col-lg-6 col-md-5 col-sm-5 col-xs-10'>
              <label for="campo_busqueda">
                <%= t("mio.campo_busqueda") %>
              </label> 
            </div>

            <div class='col-lg-4 col-md-5 col-sm-5 col-xs-10'>
              <%#= select_tag "campo_busqueda", options_for_select([ "Todos", "Título del curso", "Temática", "Información" ],params[:campo_busqueda]), {:class => "selectpicker", 'data-width' => "100%"} %>
              <%= select_tag "campo_busqueda", options_for_select([ t("mio.campo_busqueda_todos"), t("mio.campo_busqueda_titulo"), t("mio.campo_busqueda_tematica"), t("mio.campo_busqueda_informacion") ], session[:campo_busqueda]), {:class => "selectpicker", 'data-width' => "100%"} %>
            </div>
          </div>

          <div class="row form-group">
            <div class='col-lg-6 col-md-5 col-sm-5 col-xs-10'>
              <label for="orden_busqueda">
                <%= t("mio.orden") %> 
              </label>
            </div>
            <div class='col-lg-4 col-md-5 col-sm-5 col-xs-10'>
              <%#= select_tag "orden_busqueda", options_for_select([ "Título del curso", "Instituciones", "Plataformas", "Puntuación obtenida" ],params[:orden_busqueda]), {:class => "selectpicker", 'data-width' => "100%"} %>
              <%= select_tag "orden_busqueda", options_for_select([ t("mio.orden_busqueda_titulo"), t("mio.orden_busqueda_instituciones"), t("mio.orden_busqueda_plataformas"), t("mio.orden_busqueda_puntuacion") ],session[:orden_busqueda]), {:class => "selectpicker", 'data-width' => "100%"} %>
            </div>
          </div>
        </h3>
      <% end %>

    </div>

app/views/layouts/_cabecera.html.erb
  <div id='presentacion' class='container-fluid' >
    <div class='col-lg-12 col-md-12 col-sm-12 hidden-12'>
    <a href="#content">UNED</a>
    </div>
    <div class='col-lg-12 col-md-12 col-sm-12 hidden-12'>
      <%= link_to_unless_current "English", locale: "en", user: params[:user], curso: params[:curso] %> |
      <%= link_to_unless_current "Español", locale: "es", user: params[:user], curso: params[:curso] %>
    </div>
    
    <%= link_to home_index_url do %>
      <div class='col-lg-4 col-md-4 col-sm-12 hidden-12 text-center'>
        <h1>YourMOOC4all</h1>
      </div>
    <% end %>
    <div class='col-lg-7 col-md-7 col-sm-12 hidden-xs text-center'>
      <h2><%= t("mio.cabecera_texto") %></h2>
    </div>
  </div>

  <%= breadcrumbs style: :bootstrap %>

  <div class="container layout-contenido">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>

app/views/layouts/_enlaces.html.erb
    <div id='enlaces'class='row col-lg-4 col-md-5 col-sm-6 col-xs-12 text-center'>
      <div class='jumbotron'>
        <%= render "devise/shared/links" %>
      </div>
    </div>

app/views/layouts/_pie.html.erb
<div id="content">
	<div id="section4" class="container-fluid">

		<span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= t("mio.actualizacion") %>
				<br />
				<br />
		<div class="row">
			<div class="col-lg-5 col-md-5 col-sm-12 hidden-xs">
				<h3><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> <%= t("mio.objetivos_cabecera") %></h3>
				<hr />
				<br />
				<p><%= raw(t("mio.objetivos")) %></p>
				<br />
			</div>
			<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"> 
				<h3><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= t("mio.proyecto_cabecera") %></h3>
				<hr />
				<br />
				Pedro Manuel Muñoz Morales
				<br />
				<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:pmunoz85@alumno.uned.es">	pmunoz85@alumno.uned.es</a>
				<br />
				<br />
				Director: Francisco Iniesto Carrasco
				<br />
				The Open University, Reino Unido				
				<br />
				<br />
				Codirectora: Covadonga Rodrigo San Juan
				<br />
				Lenguajes y Sistemas Informáticos
				<br />
				<br />
				UNED - Grado en Ingeniería Informática
				<br />
			    © 2018 <%= t("mio.pfg") %>
				<br />
			</div>
			<div class="col-lg-4 col-md-4 hidden-sm hidden-xs"> 
				<h3><span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span> <%= t("mio.tecnologias_cabecera") %></h3> 
				<hr />
				<br />
				<p><%= raw(t("mio.tecnologias")) %></p>
			</div>
		</div>

	</div>
</div>

app/views/layouts/_usuario.html.erb
    <div id='enlaces'class='row col-lg-4 col-md-5 col-sm-6 col-xs-12 text-center'>
      <div class='jumbotron'>
        <div class='row'>
          <div class='row col-lg-12 col-md-12 col-sm-12 col-xs-12'>
            <%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do %>
              <span class='glyphicon glyphicon-off'></span>
              <%= t('mio.cerrar_sesion') %>
            <% end %>
          </div>
    
          <div class='row col-lg-12 col-md-12 col-sm-12 col-xs-12'>
            <a href="<%= edit_user_registration_path %>"><span class='glyphicon glyphicon-edit'></span> <%= current_user.email %></a>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/administrador.html.erb
<!DOCTYPE html>
<html lang=es>
<head>
  <meta charset="utf-8">
  <title>YourMOOC4all</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Sitio de la administración de la aplicación">
  <meta name="author" content="Pedro Manuel Muñoz Morales">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <% if params[:locale] == "es" then %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/i18n/defaults-es_ES.js"></script>
  <% end %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "YOURMOOC4all", "#", :class => "navbar-brand" %>
        <%#= image_tag("images9.jpeg", :size => "50") %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%=menu_activo('administrador')%>"><a href="<%= administrador_index_url %>"><span class='glyphicon glyphicon-home'></span> Home</a></li>
<!--
					<li class='<%=menu_activo('subtitulos')%>'><a href='<%= subtitulos_url %>'><span class='glyphicon glyphicon-inbox'></span> Subtitulos</a></li>
					<li class='<%=menu_activo('audios')%>'><a href='<%= audios_url %>'><span class='glyphicon glyphicon-inbox'></span> Audios</a></li>
					<li class='<%=menu_activo('transcripciones')%>'><a href='<%= transcripciones_url %>'><span class='glyphicon glyphicon-inbox'></span> Transcripciones</a></li>
-->
					<li class='<%=menu_activo('cursos')%>'><a href='<%= cursos_url %>'><span class='glyphicon glyphicon-blackboard'></span> <%= t('mio.cursos') %></a></li>
          <li class="dropdown <%=menu_activo('users')%><%=menu_activo('tipostramites')%><%=menu_activo('registrations')%><%=menu_activo('proveedores')%><%=menu_activo('universidades')%><%=menu_activo('idiomas')%>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class='<%=menu_activo('universidades')%>'><a href='<%= universidades_url %>'><span class='glyphicon glyphicon-education'></span> <%= t('mio.instituciones') %></a></li>
              <li class='<%=menu_activo('proveedores')%>'><a href='<%= proveedores_url %>'><span class='glyphicon glyphicon-comment'></span> <%= t('mio.plataformas') %></a></li>
              <li class='<%=menu_activo('idiomas')%>'><a href='<%= idiomas_url %>'><span class='glyphicon glyphicon-bullhorn'></span> <%= t('mio.idiomas') %></a></li>
              <li class="divider"></li>
              <li class="<%=menu_activo('users')%>"><a href="<%= users_url %>"><span class='glyphicon glyphicon-log-in'></span> <%= t('mio.usuarios') %></a></li>
              <li class="divider"></li>
              <li class="<%=menu_activo('registrations')%>"><a href="<%= edit_user_registration_path %>"><span class='glyphicon glyphicon-edit'></span> <%= current_user.email %></a>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to_unless_current "English", locale: "en" if params[:locale] == 'es' %><%= link_to_unless_current "Español", locale: "es" if params[:locale] == 'en'  %>
          </li>
        </ul>

        <%= form_tag administrador_index_path, :method => :get, :class => 'navbar-form navbar-left', :role => 'search' do %>
          <div class="form-group">
            <%= search_field_tag :buscar, @buscar, :placeholder => t('mio.unir_palabras'), :autofocus => true, :class => 'form-control' %>
          </div>
          <button type="submit" class="btn btn-default"><span class='glyphicon glyphicon-search'></span></button>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do %>
              <span class='glyphicon glyphicon-off'></span>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>

  <%= breadcrumbs style: :bootstrap %>
  
  <div class="container layout-contenido">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  
  </div>

  <%= render partial: 'layouts/pie'  %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=es>
<head>
  <meta charset="utf-8">
  <title>YourMOOC4all</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Sitio de la administración de la aplicación">
  <meta name="author" content="Pedro Manuel Muñoz Morales">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <% if params[:locale] == "es" then %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/i18n/defaults-es_ES.js"></script>
  <% end %>
</head>

<body style='padding: 0'>

  <%= render partial: 'layouts/cabecera'  %>

  <div id='centro' class='container-fluid' >
    <%= render partial: 'layouts/buscador'  %>

    <%= render partial: 'layouts/enlaces'  %>
  </div>


  <div class="container layout-contenido">

    <%= yield %>
  
  </div>


  <%= render partial: 'layouts/pie'  %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang=es>
<head>
  <meta charset="utf-8">
  <title>YourMOOC4all</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Búscador de cursos MOOC centralizado">
  <meta name="author" content="Pedro Manuel Muñoz Morales">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body style='padding: 0'>

  <%= render partial: 'layouts/cabecera'  %>

  <div id='centro' class="container-fluid">

 		<%= yield %>

    <% if current_user.nil? %>
      <%= render partial: 'layouts/enlaces'  %>
    <% end %>
  
  </div>


  <%= render partial: 'layouts/pie'  %>

</body>
</html>

app/views/layouts/inicio.html.erb
<!DOCTYPE html>
<html lang=es>
<head>
  <meta charset="utf-8">
  <title>YourMOOC4all</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Búscador de cursos MOOC centralizado">
  <meta name="author" content="Pedro Manuel Muñoz Morales">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <% if params[:locale] == "es" then %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/i18n/defaults-es_ES.js"></script>
  <% end %>

</head>
<body style='padding: 0'>

  <%= render partial: 'layouts/cabecera' %>

  <style>
    #centro {padding-top: 50px; padding-bottom: 50px; padding-left: 50px; padding-right: 0px; margin-bottom: 0px; color: #000; background-color: #fff;}
  </style>

  <% unless controller_name == 'evaluaciones' then %>
    <div id='centro' class='container-fluid' >
      <%= render partial: 'layouts/buscador'  %>
    
      <%= render partial: 'layouts/usuario'  %>
    </div>
  <% end %>

  <div class="container layout-contenido">
    <%= yield %>
  </div>

  <%= render partial: 'layouts/pie'  %>

</body>
</html>